services:
  - type: web
    name: audio-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/backend.py"
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: dash-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server"